#默认公共配置
spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #使用redis作为缓存
#  cache:
#    type: redis
  #序列化时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #服务注册名
  application:
    name: hvisions-subway
  #国际化配置
  messages:
    basename: i18n/messages
    encoding: utf-8
    cache-duration: 3600
#开启所有的健康监控信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS